<?php

namespace App\Support;

use Illuminate\Support\Facades\File;

/**
 * Taivutus: drills that make the learner CHANGE a sentence, not recall one.
 *
 * The rest of the course teaches whole sentences, which is fast and immediately
 * usable - but memorizing "Mä otan kahvin" never teaches anyone to produce
 * "Mä en ota kahvii". Finnish carries its meaning in the endings, so somewhere
 * the learner has to practise bending them. That's this.
 *
 * Content is hand-written (database/transforms/*.json) on purpose: consonant
 * gradation, vowel harmony and the everyday irregulars (kotiin → kotona) can't
 * be generated by rule without confidently teaching wrong Finnish.
 */
class Transforms
{
    /** Parsed sets, keyed by id - built once per request. */
    private static ?array $sets = null;

    /** Every set, in filename order. */
    public static function all(): array
    {
        if (self::$sets !== null) {
            return array_values(self::$sets);
        }

        $sets = [];

        foreach (File::glob(database_path('transforms').'/*.json') as $path) {
            $data = json_decode(File::get($path), true);
            if (! is_array($data) || ! isset($data['items'])) {
                continue;
            }

            $data['id'] = preg_replace('/^\d+-/', '', pathinfo($path, PATHINFO_FILENAME));
            $sets[$data['id']] = $data;
        }

        self::$sets = $sets;

        return array_values($sets);
    }

    public static function find(?string $id): ?array
    {
        if ($id === null) {
            return null;
        }

        self::all();

        return self::$sets[$id] ?? null;
    }

    /** Catalog entries without the items - enough to render the index. */
    public static function index(): array
    {
        return array_map(fn (array $s) => [
            'id' => $s['id'],
            'emoji' => $s['emoji'] ?? '🔧',
            'title' => $s['title'],
            'rule' => $s['rule'] ?? '',
            'summary' => $s['summary'] ?? '',
            'level' => $s['level'] ?? 'A1',
            'items_count' => count($s['items']),
        ], self::all());
    }
}
