<script setup>
const UPDATED = 'July 14, 2026'
</script>

<template>
  <div class="legal">
    <div class="page-top">
      <router-link to="/" class="home-link">‹ Home</router-link>
    </div>

    <h1>Terms of service</h1>
    <p class="muted updated">Last updated {{ UPDATED }}</p>

    <p>
      These are the terms for using SaunaSpeak (saunaspeak.com). Short version:
      be a normal human, the free path stays free, subscriptions cancel cleanly,
      and the AI characters are language practice - not advisors.
    </p>

    <h2>The service</h2>
    <p>
      SaunaSpeak teaches spoken Finnish through short daily sessions, spaced
      repetition, audio and AI conversation practice. The core learning path is
      free. Löyly+ is an optional paid subscription that adds AI features
      (Sauna Chat, Situations, AI feedback, weekly insights).
    </p>

    <h2>Your account</h2>
    <ul>
      <li>You need to be at least 13 years old (or the digital-consent age in your country).</li>
      <li>Keep your password to yourself; you're responsible for what happens under your login.</li>
      <li>One account per person - progress and streaks are personal by design.</li>
    </ul>

    <h2>Löyly+ subscriptions</h2>
    <ul>
      <li>Billed monthly (€4.99) or yearly (€39.99) through Stripe, renewing automatically until cancelled.</li>
      <li>Cancel any time from your profile - you keep access until the end of the period you've paid for, and are not charged again.</li>
      <li>If a payment fails, Löyly+ features pause until it's settled; your learning data is never touched.</li>
      <li>Prices may change; existing subscribers get clear notice before any change affects them.</li>
    </ul>

    <h2>Fair use</h2>
    <ul>
      <li>Don't abuse the AI features (automated scraping, bulk generation, attempting to make the characters produce harmful content). Daily message caps exist to keep the service affordable for everyone.</li>
      <li>Don't try to break, overload or reverse the service.</li>
      <li>Lesson content, audio and the Väinö character are SaunaSpeak's; personal, non-commercial use only.</li>
    </ul>

    <h2>The honest disclaimers</h2>
    <ul>
      <li>AI replies are generated by language models and can be wrong. Corrections aim to teach everyday spoken Finnish, not certified translation. Double-check anything important.</li>
      <li>The service is provided "as is" - we work hard on uptime and data safety but can't guarantee either perfectly. Our total liability is capped at what you've paid us in the last 12 months.</li>
      <li>We may update features and these terms; material changes will be announced in the app or by email.</li>
    </ul>

    <h2>Ending things</h2>
    <p>
      You can delete your account (and export your data first) from your profile at
      any time. We can suspend accounts that break these terms, with a warning
      unless the abuse is severe.
    </p>

    <h2>Contact</h2>
    <p>
      <a href="mailto:mail@saunaspeak.com">mail@saunaspeak.com</a> - a human reads it.
    </p>

    <p class="muted footer-links">
      <router-link to="/privacy">Privacy policy</router-link> ·
      <router-link to="/">Home</router-link>
    </p>
  </div>
</template>

<style scoped>
.legal { max-width: 640px; margin: 0 auto; padding: 16px 4px 60px; text-align: left; }
.page-top { margin-bottom: 20px; }
.home-link { color: var(--text-dim); font-size: 14px; font-weight: 600; }
.legal h1 { font-size: 28px; margin-bottom: 4px; }
.updated { font-size: 13px; margin-bottom: 20px; }
.legal h2 { font-size: 18px; margin: 26px 0 8px; }
.legal p { font-size: 14.5px; line-height: 1.65; color: var(--text-dim); margin-bottom: 10px; }
.legal ul { padding-left: 20px; display: flex; flex-direction: column; gap: 8px; margin: 8px 0 12px; }
.legal li { font-size: 14.5px; line-height: 1.6; color: var(--text-dim); }
.legal b { color: var(--text); }
.legal a { color: var(--accent); text-decoration: underline; text-underline-offset: 2px; }
.footer-links { margin-top: 30px; font-size: 13px; }
</style>
